name: 'npm Build Project'
description: 'This action configures node and builds a project using npm'
inputs:
  node_version:
    required: true
    description: 'The required node version'
  install_command:
    required: false
    description: 'The npm install command'
  build_command:
    required: false
    description: 'The npm build command'
  github_token:
    required: true
    description: 'Access token to authenticate with GitHub package registry'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@ukhomeoffice'
        
    - name: Install npm dependencies
      run: npm --loglevel warn ${{ inputs.install_command || 'ci' }}
      shell: bash
      env: 
        NODE_AUTH_TOKEN: ${{ input.github_token }}

    - name: Build project
      run: npm run ${{ inputs.build_command || 'build' }}
      shell: bash
