name: 'Trivy Scan Docker Image'
description: 'Builds and scans a docker image using Trivy'
inputs:
  sarif:
    required: true
    description: 'Whether to generate a sarif report, otherwise a table is generated'
  severity:
    required: true
    description: 'The severity of the vulnerabilities to report.'
    
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: localbuild/testimage:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.11.2
      with:
        image-ref: 'localbuild/testimage:latest'
        ignore-unfixed: true
        format: ${{ inputs.sarif == 'true' && 'sarif' || 'table' }} 
        output: ${{ inputs.sarif == 'true' && 'trivy-results.sarif' || '' }}
        severity: ${{ inputs.severity }}
        exit-code: '1'
        vuln-type: 'library'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: inputs.sarif == 'true'
      with:
        sarif_file: 'trivy-results.sarif'
