name: 'Publish Docker Image'
description: 'Authorises a repository, builds and pushes a docker image'
inputs:
  registry:
    required: false
    description: 'The registry to use'
  username:
    required: true
    description: 'The registry username'
  password:
    required: true
    description: 'The registry password'
  image:
    required: true
    description: 'The docker image name'
  tag:
    required: true
    description: 'The tag to use for the docker image'
  tag_latest:
    required: true
    description: 'The tag to use for the docker image'

runs:
  using: 'composite'
  steps:

    - name: Login to repository
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry || 'quay.io' }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Calculate metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: |
          type=raw,value=${{ inputs.tag }}
          type=raw,value=latest,enable=${{ inputs.tag_latest || false }}

    - name: Push container
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
