name: 'Anchore Scan Docker - Gradle'
on:
  workflow_call:
    inputs:
      javaVersion:
        required: false
        type: string
        default: '17'
      buildCommand:
        required: false
        type: string
      registry:
        required: false
        type: string
      image:
        required: true
        type: string
      ecr:
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: 'Anchore Scan'
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        uses: UKHomeOffice/sas-github-workflows/.github/actions/gradle-build-project@v2
        with:
          java_version: ${{ inputs.javaVersion }}
          build_command: ${{ inputs.buildCommand }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Anchore Scan image
        uses: UKHomeOffice/sas-github-workflows/.github/actions/docker-scan@v2

      - name: Publish image to Docker
        if: |
          contains(github.event.pull_request.labels.*.name, 'smoketest') &&
          inputs.ecr == false
        uses: UKHomeOffice/sas-github-workflows/.github/actions/docker-publish@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKER_USER_NAME || secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.QUAY_ROBOT_TOKEN }}
          tag: ${{ github.event.pull_request.head.sha }}
          image: ${{ inputs.image }}

      - name: Publish image to ECR
        uses: UKHomeOffice/sas-github-workflows/.github/actions/docker-ecr-publish@v2
        if: |
          contains(github.event.pull_request.labels.*.name, 'smoketest') &&
          inputs.ecr == true
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          tag: ${{ github.event.pull_request.head.sha }}
          image: ${{ inputs.image }}
