name: 'Anchore Scan Docker - npm'
on:
  workflow_call:
    inputs:
      nodeVersion:
        required: false
        type: string
        default: '18.x'
      installCommand:
        required: false
        type: string
      buildCommand:
        required: false
        type: string
      lintCommand:
        required: false
        type: string
      registry:
        required: false
        type: string
      image:
        required: true
        type: string
      ecr:
        type: boolean
        default: false
      checkoutSubmodule:
        required: false
        description: 'Whether to checkout submodules.'
        type: string
        default: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: 'Anchore Scan'
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.checkoutSubmodule }}

      - name: Build project
        uses: UKHomeOffice/sas-github-workflows/.github/actions/npm-build-project@v2
        with:
          node_version: ${{ inputs.nodeVersion }}
          install_command: ${{ inputs.installCommand }}
          build_command: ${{ inputs.buildCommand }}

      - name: Anchore Scan image
        uses: UKHomeOffice/sas-github-workflows/.github/actions/docker-scan@v2

      - name: Publish image to Docker
        if: |
          contains(github.event.pull_request.labels.*.name, 'smoketest') &&
          inputs.ecr == false
        uses: UKHomeOffice/sas-github-workflows/.github/actions/docker-publish@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKER_USER_NAME || secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.QUAY_ROBOT_TOKEN }}
          tag: ${{ github.event.pull_request.head.sha }}
          image: ${{ inputs.image }}

      - name: Publish image to ECR
        uses: UKHomeOffice/sas-github-workflows/.github/actions/docker-ecr-publish@v2
        if: |
          contains(github.event.pull_request.labels.*.name, 'smoketest') &&
          inputs.ecr == true
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          tag: ${{ github.event.pull_request.head.sha }}
          image: ${{ inputs.image }}
