name: 'SemVer Tag'
on:
  workflow_call:
    inputs:
      nodeVersion:
        required: false
        type: string
        default: '18.x'
      installCommand:
        required: false
        type: string
        default: 'ci --ignore-scripts'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  tag:
    name: 'Main SemVer Tag'
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ukhomeoffice'

      - name: Calculate SemVer value
        id: calculate
        uses: UKHomeOffice/sas-github-workflows/.github/actions/calculate-semver-value@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_to_highest: ${{ github.base_ref == 'main' }}

      - name: Bump Release Version
        run: |
          npm --no-git-tag-version version ${{ steps.calculate.outputs.version }}
        shell: bash

      - name: Install npm dependencies
        run: |
          npm --loglevel warn ${{ inputs.installCommand }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish npm package
        run: |
          npm publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Tag Repository
        uses: UKHomeOffice/semver-tag-action@v4
        with:
          tag: ${{ steps.calculate.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
