name: 'Semver Tag Docker'
on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
      image:
        required: true
        type: string
      ecr:
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  docker:
    name: 'Main Semver Tag'
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Calculate SemVer value
        id: calculate
        uses: UKHomeOffice/sas-github-workflows/.github/actions/calculate-semver-value@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_to_highest: ${{ github.base_ref == 'main' }}

      - name: Publish image to ECR
        uses: UKHomeOffice/sas-github-workflows/.github/actions/docker-ecr-publish@v2
        if: inputs.ecr == true
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          tag: ${{ steps.calculate.outputs.version }}
          tag_latest: ${{ github.base_ref == 'main' }}
          image: ${{ inputs.image }}

      - name: Publish image to Docker
        uses: UKHomeOffice/sas-github-workflows/.github/actions/docker-publish@v2
        if: inputs.ecr == false
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKER_USER_NAME || secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.QUAY_ROBOT_TOKEN }}
          tag: ${{ steps.calculate.outputs.version }}
          tag_latest: ${{ github.base_ref == 'main' }}
          image: ${{ inputs.image }}

      - name: Tag Repository
        uses: UKHomeOffice/semver-tag-action@v3
        with:
          tag: ${{ steps.calculate.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
