name: 'SemVer label Check and Increment package.json - npm'
on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: 'Calculate SemVer Value and Increment'
    if: |
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest

    steps:
      - name: Parse the SemVer label
        id: label
        uses: UKHomeOffice/match-label-action@v1
        with:
          labels: minor,major,patch
          mode: singular

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Reset Branch from Main Version
        id: compare
        run: |
          localFile=$(cat package.json)
          originFile=$(git show origin/main:package.json)
          localVersion=$(echo $localFile | jq -r '.version')
          originVersion=$(echo $originFile | jq -r '.version')
          if [ "$localVersion" != "$originVersion" ]; then
            npm --no-git-tag-version version $originVersion
          fi
        shell: bash

      - name: Bump Release Version
        run: echo "NEW_VERSION=$(npm --no-git-tag-version version ${{ steps.label.outputs.matchedLabels }})" >> $GITHUB_ENV
        shell: bash

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        shell: bash

      - name: Commit package.json Change
        run: |
          git add "package.json"
          git commit --amend --no-edit
          git push --set-upstream origin ${{ github.head_ref }} --force
        shell: bash
