name: 'Test - npm'
on:
  workflow_call:
    inputs:
      nodeVersionMatrix:
        required: false
        type: string
        default: '[ "18.x", "19.x" ]'
      installCommand:
        required: false
        type: string
      buildCommand:
        required: false
        type: string
      auditCommand:
        required: false
        type: string
      lintCommand:
        required: false
        type: string
      testCommand:
        required: false
        type: string
      osDependencies:
        required: false
        type: string
      dockerComposeCommand:
        required: false
        type: string
      dockerComposeComponents:
        required: false
        type: string
      healthcheckScript:
        required: false
        type: string
      checkoutSubmodule:
        required: false
        description: 'Whether to checkout submodules.'
        type: string
        default: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Unit and Integration Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ${{ fromJson(inputs.nodeVersionMatrix) }}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.checkoutSubmodule }}

      - name: Build project
        uses: UKHomeOffice/sas-github-workflows/.github/actions/npm-build-project@v2
        with:
          node_version: ${{ matrix.node_version }}
          install_command: ${{ inputs.installCommand }}
          build_command: ${{ inputs.buildCommand }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run audit
        run: npm run ${{ inputs.auditCommand || 'audit' }}
        shell: bash

      - name: Run lint
        run: npm run ${{ inputs.lintCommand || 'lint' }}
        shell: bash

      - name: Start integration infrastructure
        uses: UKHomeOffice/sas-github-workflows/.github/actions/start-integration-infrastructure@v3
        with:
          os_dependencies: ${{ inputs.osDependencies }}
          docker_compose_command: ${{ inputs.dockerComposeCommand }}
          docker_compose_components: ${{ inputs.dockerComposeComponents }}
          healthcheck_script: ${{ inputs.healthcheckScript }}

      - name: Run tests
        run: npm ${{ inputs.testCommand || 'test' }}
        shell: bash
