name: 'Test - Gradle'
on:
  workflow_call:
    inputs:
      javaVersion:
        required: false
        type: string
        default: '17'
      buildCommand:
        required: false
        type: string
      testCommand:
        required: false
        type: string
      osDependencies:
        required: false
        type: string
      dockerComposeCommand:
        required: false
        type: string
      dockerComposeComponents:
        required: false
        type: string
      healthcheckScript:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Unit and Integration Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        uses: UKHomeOffice/sas-github-workflows/.github/actions/gradle-build-project@v1
        with:
          java_version: ${{ inputs.javaVersion }}
          build_command: ${{ inputs.buildCommand }}

      - name: Start integration infrastructure
        uses: UKHomeOffice/sas-github-workflows/.github/actions/start-integration-infrastructure@v1
        with:
          os_dependencies: ${{ inputs.osDependencies }}
          docker_compose_command: ${{ inputs.dockerComposeCommand }}
          docker_compose_components: ${{ inputs.dockerComposeComponents }}
          healthcheck_script: ${{ inputs.healthcheckScript }}

      - name: Run tests
        run: ./gradlew ${{ inputs.testCommand || 'test --no-daemon' }}
        shell: bash
